package cc.ddrpa.dorian.elias.generator.export;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

/**
 * Writes a single Liquibase formatted-sql changeset from a {@link DiffResult}.
 */
public class LiquibaseSqlExporter {

    public boolean export(DiffResult diffResult, Path outputFile, String changesetId, String author)
            throws IOException {
        if (diffResult == null || !diffResult.hasExportableSql()) {
            return false;
        }
        String content = render(diffResult, changesetId, author);
        if (content.isBlank() || !containsForwardSql(content)) {
            return false;
        }
        Files.createDirectories(outputFile.getParent());
        Files.writeString(outputFile, content, StandardCharsets.UTF_8);
        return true;
    }

    private static boolean containsForwardSql(String content) {
        for (String line : content.split("\n")) {
            String trimmed = line.trim();
            if (trimmed.isEmpty() || trimmed.startsWith("--")) {
                continue;
            }
            return true;
        }
        return false;
    }

    public String render(DiffResult diffResult, String changesetId, String author) {
        StringBuilder sb = new StringBuilder();
        sb.append("--liquibase formatted sql\n");
        sb.append("-- Generated by elias changelog-export at ").append(Instant.now()).append('\n');
        sb.append("-- Target dialect: MySQL 5.7+\n");
        sb.append("-- Note: H2 MODE=MySQL can replay common CREATE/ADD/DROP; ")
                .append("SPATIAL INDEX and CHANGE COLUMN need a MySQL jdbcUrl for baseline replay.\n");
        sb.append("-- Note: --rollback lines are structural inverses only; data is not restored.\n");
        List<ExportChange> destructive = diffResult.getDestructiveChanges();
        if (!destructive.isEmpty()) {
            sb.append("-- destructive:\n");
            for (ExportChange change : destructive) {
                sb.append("--   - ").append(change.getSummary()).append('\n');
            }
        } else {
            sb.append("-- destructive: none\n");
        }
        sb.append("--changeset ").append(author == null || author.isBlank() ? "elias" : author)
                .append(':').append(changesetId)
                .append(" endDelimiter:;\n");
        sb.append("--comment: net schema diff exported by elias\n");
        for (ExportChange change : diffResult.getChanges()) {
            sb.append("-- ").append(change.getKind()).append(": ").append(change.getSummary())
                    .append('\n');
            appendSqlStatements(sb, change.getSql(), false);
        }
        // Liquibase executes --rollback lines in listed order; emit reverse of forward changes.
        List<ExportChange> reverse = new ArrayList<>(diffResult.getChanges());
        Collections.reverse(reverse);
        for (ExportChange change : reverse) {
            String rollback = change.getRollbackSql();
            if (rollback == null || rollback.isBlank()) {
                continue;
            }
            appendSqlStatements(sb, rollback, true);
        }
        return sb.toString();
    }

    private static void appendSqlStatements(StringBuilder sb, String sqlBlob, boolean rollback) {
        String[] parts = sqlBlob.split(";");
        for (String part : parts) {
            String sql = part.trim();
            if (sql.isEmpty()) {
                continue;
            }
            if (rollback) {
                sb.append("--rollback ").append(sql).append(";\n");
            } else {
                sb.append(sql).append(";\n");
            }
        }
    }

    public String summarizeDestructive(DiffResult diffResult) {
        return diffResult.getDestructiveChanges().stream()
                .map(ExportChange::getSummary)
                .collect(Collectors.joining("\n"));
    }
}
